#!/bin/bash
#
# Delete the directories generated by the packaging

rm -rf UnrealProject/Binaries/
rm -rf UnrealProject/Build/
rm -rf UnrealProject/DerivedDataCache/
rm -rf UnrealProject/Intermediate/
rm -rf UnrealProject/Saved/
rm -rf UnrealProject/LinuxNoEditor/
