TODO list for the NaivePhysics project

* train, after ED
** mask, depth and scene
** check at least one object visible and one occlusion
   a posteriori: just parse the status.txt
** random trajectories (not only parallel, we want hits!)
** random spheres and walls
   walls with left/right rotations, mobile/immobile spheres
* bugs
** do we need depth for train samples? YES
   If so there is a bug because all actors are visible on depth but not in scene
   The same apply for mask
** a minor bug in C1_dynamic_1?
   Sometimes the main actor move slower in 2nd than in 1st iteration?
   Lead to a check failure in all cases but this is a waste of time
   and resources
* Python side
** test -j2 and -j3
** fix the bug in balancing jsons
** should be better/simpler with a randomization in python
   thus the json would have one entry per run, all parameters already fixed
* lua/engine side
** variability
*** random cloud position/orientaion/speed
*** random light position/number -> variable shadows
*** random camera position -> random position and point of view, constrained orientation
*** for now all spheres/walls have the same material within a run, is it ok?
** add a little delay (3 to 4 ticks?) because textures take time to be correctly displayed
   also the first image is all black!
** is the motion blur a problem? NOT NOW
   see https://answers.unrealengine.com/questions/17881/graphic-settings-disable-motion-blur.html
** optimize checks in C1_dynamic_1
   -> detect failures right after iterationType 5, not after the whole run!!
   -> as done in C1_dynamic_2 block
** format params.json to have spaces and new lines
** refactor status.txt
* run on a headless cluster
** The problem is remote openGl rendering
** with DISPLAY=:0 that works remotely but corrupt the host's X server!
** http://www.virtualgl.org can be a solution
