TODO list for the NaivePhysics project

* different classes of motion
  static, sliding, rolling, falling, walking (agent)
* train, after ED
** check at least one object visible and one occlusion
   a posteriori: just parse the status.txt?
** random spheres and walls
   walls with left/right rotations, mobile/immobile spheres
   non parallel trajectories for spheres
   world limit with walls or sky randomly
* bugs
** a minor bug in C1_dynamic_1?
   Sometimes the main actor move slower in 2nd than in 1st iteration?
   Lead to a check failure in all cases but this is a waste of time
   and resources
* Python side
** test -j2 and -j3
** fix the bug in balancing jsons
** should be better/simpler with a randomization in python
   thus the json would have one entry per run, all parameters already fixed
* lua/engine side
** variability
*** random cloud position/orientaion/speed
*** random light position/number -> variable shadows
*** random camera position -> random position and point of view, constrained orientation
*** for now all spheres/walls have the same material within a run, is it ok?
** add a little delay (3 to 4 ticks?) because textures take time to be correctly displayed
   also the first image is all black!
** optimize checks in C1_dynamic_1
   -> detect failures right after iterationType 5, not after the whole run!!
   -> as done in C1_dynamic_2 block
** format params.json to have spaces and new lines
** refactor status.txt
* run on a headless cluster
** The problem is remote openGl rendering
** with DISPLAY=:0 that works remotely but corrupt the host's X server!
** http://www.virtualgl.org can be a solution
